### PR TITLE
Feature/basic footer

### PR DESCRIPTION
**Pull request by shalinidc**
Created the clone of the footer by,
- Hand coding the HTML structure for footer
- Adding styles for the same 

To be noted,
- Footer not responsive

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This looks really great in the laptop and larger views, 1024px and up! I'm going to accept this pull request as is, as it follows our [contribution process and coding standards](https://github.com/chingu-voyage3/toucans-06/wiki/Code-Standards,-Process,-Visions,-and-Goals#specific-contributionmerge-process) and doesn't introduce any bugs as far as I can tell right now. We still need a review from @miraclmoore or @willatauro before merging this into `staging`.

Here are some suggestions to improve the code. Keep in mind that these are suggestions and are not required for this pull request to be merged into `staging`. Fix what you can and feel you need to fix. I hope this is helpful! :sunny:

### index.html

- Copy/pasting the HTML code into https://validator.w3.org/nu/#textarea shows about 8 errors. However, all 8 of these errors can be solved by fixing the closing anchor tag on line 240 (`<a>` to `</a>`). :)

- The "Connect with Us" section would be perfect for the `<address>` element. Replacing `<div class="footer-connectwithus-section col-block">` with `<address class="col-block">` on line 230, changing `</div>` to `</address>` on line 242, and then changing the `.footer-connectwithus-section` to `address` in your CSS should do the trick, if you're interested in making that change.

- On line 216, you have `Before & After`. I think it's best practice to replace the ampersand with the `&amp;` [escape code](http://www.escapecodes.info/). This helps to avoid any unintentional issues with a browser accidentally thinking that ampersand is useful for some reason.

- Did you mean for `.footer-outsolutions-section` to be `.footer-oursolutions-section`, with an `r`? It's not a big deal, but could lead to confusion for developers looking at the code later on.

- lines 246-253 have anchor tags without `href` attributes. I guess it works and it's valid HTML, but to me, it's usually not too much trouble to fill it in with `href="#"`. In my browser, when I hover over those links, they don't work as expected (no finger pointer) and I'm thinking that's because the browser is not seeing them as links. Issues like this are helpful because it forces me to look up the specs and learn what's expected from browsers. I found [this](https://stackoverflow.com/a/10510353) which links to [this spec](https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element). I think for our project's purposes, this quote from the first link is why we'll want to add href to those anchor tags at some point:

   > As far as semantics and styling is concerned, the <a> element isn't a link (:link) unless it has an [href] attribute. A side-effect of this is that an <a> element without [href] won't be in the tabbing order by default.

- Instead of using `section-header`, I think it's better to use heading elements. In this case, `h2` is probably most appropriate. This puts those footer sections into the document outline making it easier for search engines and screen readers to find and use them. You can read more [here](https://learn.shayhowe.com/html-css/writing-your-best-code/) in the `Make Use of Semantic Elements` section.

- The `h3` on line 233 shouldn't be there because it appears that it's being used for styling instead of document outline header hierarchy. You can see the document outline by copy/pasting your code into the [HTML validator](https://validator.w3.org/nu/#textarea), selecting `outline` in the show section, and clicking `Check`. You will have to fix the closing anchor tag on line 240 in order for the checker to be able to calculate the document outline.

### style.css

- There are no problems when I copy/paste your CSS code into the [CSS Validator](https://jigsaw.w3.org/css-validator/#validate_by_input)!

- Even though your use of `float` works, I think contemporary CSS design is moving towards Flexbox and Grid instead. If this were a real-world project, I can imagine a team not allowing floats to dictate layout like this. For our project, it's fine. It does take a little while to get used to positioning elements with Flexbox and Grid, however in terms of employability (so I've been told) and staying up-to-date on current CSS positioning methods, you'll want to invest some time into learning these tools. Here's what I used to learn flexbox better: [Flexbox Zombies](http://flexboxzombies.com/). Here's one I haven't used yet for Grid: [CSS Grid Garden](http://cssgridgarden.com/).

- I like your use of `calc` on line 92!

- You can style the `<footer> element as needed.` This could simplify your CSS a little, but for this project, it's fine the way you have it.

- You have some relatively specific (qualified) selectors:

   `.footer-sections ul li a` (119)
   and
   `.footer-sections ul li a:hover` (127)

   Generally, [you'll want to keep your selectors three or less levels deep](https://csswizardry.com/2012/05/keep-your-css-selectors-short/). In these cases, I think best practice is to create a new class, maybe something like `footer-list-item-anchor`. Here's [another source](https://learn.shayhowe.com/html-css/writing-your-best-code/), in the `Build Proficient Selectors` section.

- You have some qualified selectors, which [some say should be avoided](https://csswizardry.com/2012/07/quasi-qualified-css-selectors/):

   `.footer-sections span.section-header` (137)
   and
   `.social a span.twitter` (172)

**Comment by shalinidc** [comment]
Thank you for the in depth analysis @camper-fcc. This for sure is going to help me a lot in getting better. I am going to work on all the above aspects this weekend and update the pull request with the updated changes.

**Comment by shalinidc** [comment]
Hi @camper-fcc, I have made most of the changes as mentioned below:
index.html
1)This is the only one which I couldn't find - the unclosed <a> tag.
2)Added Address tag.
3)Added escape code for ampersend. Something which i learnt new. :)
4)Corrected to oursolutions. 
5)Added href attributes to all anchor tags.
6)Changed the span elements into h2 tags.
7)Corrected the h3 tag.

style.css
1)I will get started to learn more about flexbox and grid and slowly try to adapt it in my code shortly. Thank you for the references, it helps a lot.
2)Reduced the depth of the selectors as suggested.
3)I have tried avoiding the usage of qualified selectors.

I hope I have done the right thing in updating the changed in pull request, as this is the first time I am updating on a existing pull request. If I am wrong in doing it, please do let me know and any other changes as needed. :)

**Review by miraclmoore — COMMENTED** [review]
With the changes you have made @shalinidc, this looks good to me. I know you will be making some additional minor adjustments in the near future, but as of now I like what you have. 

If your ok with what we have @camper-fcc I will go ahead and merge this PR.

**Review by ghost — APPROVED** [review]
Looks great!

**Pull request merged**
